name: Build CD

on:
  push:
    branches:
      - master
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '🤖')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npx gulp clean
      - run: npx gulp html
      - run: npx gulp script
      - uses: EndBug/add-and-commit@v5
        with:
            # The arguments for the `git add` command (see the paragraph below for more info)
            # Default: '.'
            add: "dist/"

            # The name of the user that will be displayed as the author of the commit
            # Default: author of the commit that triggered the run
            author_name: Github Action CD

            # The email of the user that will be displayed as the author of the commit
            # Default: author of the commit that triggered the run
            author_email: githubaction@piuswalter.de

            # The message for the commit
            # Default: 'Commit from GitHub Actions (name of the workflow)'
            message: "🤖 compiled minified version"
        env:
            # This is necessary in order to push a commit to the repo
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
